### ISSUE TITLE
Number of LIDAR data points inconsistent

### ISSUE THREAD

**Issue by agross12** [Slamtec/rplidar_ros#104]
I am running an A1M8 LIDAR with Ubuntu 22.04 and ROS2 Humble.  The driver connects and outputs data, however the number of data points output varies by a small amount from scan to scan.  This means that my processing algorithm cannot use the data effectively.

**Comment by Plaqueoff** [comment]
Also happening on RPLidar S3 (Ubuntu 22.04 and ROS2 Humble). 
Logs from Slam Toolbox:
```
LaserRangeScan contains 3198 range readings, expected 3200
LaserRangeScan contains 3202 range readings, expected 3200
LaserRangeScan contains 3201 range readings, expected 3200
LaserRangeScan contains 3208 range readings, expected 3200
LaserRangeScan contains 3194 range readings, expected 3200
LaserRangeScan contains 3187 range readings, expected 3200
LaserRangeScan contains 3187 range readings, expected 3200
LaserRangeScan contains 3180 range readings, expected 3200
```
Config file for starting the node:
```
rplidar_node:
  ros__parameters:
    channel_type: 'serial'
    serial_port: /dev/ttyUSB0
    serial_baudrate: 1000000
    frame_id: 'laser_frame'
    inverted: false
    angle_compensate: true
    scan_mode: 'Standard'
```
